#!/usr/bin/env python

"""
Get clip content by clip id
"""

import sys
import os
import mysql.connector
from icecream import ic; ic.configureOutput(includeContext=True)
from mysql.connector.errors import DatabaseError
from clipdb import HOST, USER, PASS, DB

def eprint(*xs,**kw):
  kw['file'] = sys.stderr
  print(*xs,**kw)

args = sys.argv[1:]
if len(args) == 0:
  eprint(f"{sys.argv[0]} <id> [<id>...]")
  exit(1)
  
try:
  mydb = mysql.connector.connect(host=HOST,user=USER,password=PASS,database=DB)
except DatabaseError as e:
  eprint(f"DatabaseError(connect): {e}")
  exit(1)

sql = """SELECT value FROM clips WHERE id = %s"""

cursor = mydb.cursor()
error = False
for arg in args:
  try:
    clipid = int(arg)
  except ValueError:
    eprint(f"'{arg}' not integer")
    continue
  cursor.execute(sql,(clipid,))
  a = cursor.fetchall()
  if len(a) > 0:
    value = a[0][0]
    if value[-1] != "\n":
      print(value)
    else:
      print(value,end="")
  else:
    error = True

exit(1 if error else 0)
