#!/usr/bin/env python
import sys
import os
import requests
import bouncer
import json
from icecream import ic

url = "http://hexvision.mrflbble.com/path/to/backend.php"

def eprint(*xs,**kw):
  kw['file'] = sys.stderr
  print(*xs,**kw)

args = sys.argv[1:]
if len(args) == 0:
  eprint(f"{sys.argv[0]} <pattern> [<pattern>]")
  exit(1)

def getname(arg):
  if ":" in arg:
    namespace, name = arg.split(":",1)
  else:
    name = arg
    namespace = os.getenv("CLIPNS","_")
  return (namespace,name)

cookies = { bouncer.cookiename: bouncer.cookievalue }

found = {}
for arg in args:
  namespace, pattern = getname(arg)
  if namespace == "":
    namespace = None
  req = { "namespace": namespace, "pattern": pattern }
  j = json.dumps(req)

  r = requests.post(url,data=j,cookies=cookies)
  if r.status_code == 200:
    try:
      b = json.loads(r.text)
      ms = b['matches']
      for x in ms:
        match x:
          case { "id": x, "namespace": ns, "name": name }:
            print(f"{x} {ns}:{name}")
    except Exception as e:
      eprint("error",r,r.text,e)
  elif r.status_code == 404:
    eprint(f"{namespace}:{pattern} not found")
  elif r.status_code == 403:
    eprint(f"Access denied")
    exit(1)
  else:
    eprint(f"Returned {r.status_code}")
    eprint(r.text)
