#!/usr/bin/env python
import sys
import os
import requests
import bouncer
import json
from icecream import ic

url = "http://hexvision.mrflbble.com/path/to/backend.php"

def eprint(*xs,**kw):
  kw['file'] = sys.stderr
  print(*xs,**kw)

args = sys.argv[1:]
if len(args) < 2:
  eprint(f"{sys.argv[0]} <name> <index> [<index>...]")
  exit(1)

def getname(arg):
  if ":" in arg:
    namespace, name = arg.split(":",1)
  else:
    name = arg
    namespace = os.getenv("CLIPNS","_")
  return (namespace,name)

cookies = { bouncer.cookiename: bouncer.cookievalue }

namespace,name = getname(args.pop(0))
req = { "namespace": namespace, "name": name }
output = []
for arg in args: 
  try:
    req["index"] = int(arg)
  except ValueError:
    eprint(f"Index {arg} not an integer")
    exit(1)

  j = json.dumps(req)
  r = requests.post(url,data=j,cookies=cookies)
  if r.status_code == 200:
    try:
      b = json.loads(r.text)
      value = b["value"]
      output.append(value)
    except Exception as e:
      eprint("error",r,r.text,e)
      exit(1)
  if r.status_code == 404:
    eprint(f"{namespace}:{name} or index {arg} not found")
    exit(1)
  if r.status_code == 403:
    eprint(f"Access denied")
    exit(1)
      
print("\n".join(output))
