#!/usr/bin/env python
import sys
import os
import requests
import bouncer
import json
from icecream import ic

url = "http://hexvision.mrflbble.com/path/to/backend.php"

def eprint(*xs,**kw):
  kw['file'] = sys.stderr
  print(*xs,**kw)

def exithelp(msg=None,retval=1):
  if msg is not None:
    eprint(msg)
  eprint(f"{sys.argv[0]} <id> [<id>...]")
  exit(retval)

try:
  args = list(map(int,sys.argv[1:]))
except ValueError:
  exithelp("Arguments must be integers")

if len(args) == 0:
  exithelp("No arguments")

cookies = { bouncer.cookiename: bouncer.cookievalue }

for clipid in args:
  req = { "clipid": clipid }
  j = json.dumps(req)

  r = requests.post(url,data=j,cookies=cookies)
  if r.status_code == 200:
    try:
      b = json.loads(r.text)
      value = b["value"]
      print(value)
    except Exception as e:
      eprint("error",r,r.text,e)
      exit(1)
  if r.status_code == 404:
    print(f"Clip {clipid} not found")
    exit(1)
  if r.status_code == 403:
    print(f"Access denied")
    exit(1)
    
