#!/usr/bin/env python
import sys
import os
import requests
import bouncer
import json
from icecream import ic

url = "http://hexvision.mrflbble.com/path/to/backend.php"

def eprint(*xs,**kw):
  kw['file'] = sys.stderr
  print(*xs,**kw)

args = sys.argv[1:]
if len(args) == 0:
  eprint(f"{sys.argv[0]} <namespace pattern> [<namespace pattern>...]")
  exit(1)

cookies = { bouncer.cookiename: bouncer.cookievalue }

namespaces = set()
for namespace in args:
  req = { "namespace": namespace }
  j = json.dumps(req)

  r = requests.post(url,data=j,cookies=cookies)
  if r.status_code == 200:
    try:
      b = json.loads(r.text)
      if b["message"] == "success":
        print("\n".join(b["namespaces"]))
      else:
        raise Exception("Didn't succeed")
    except Exception as e:
      eprint("error",r,r.text,e,file=sys.stderr)
  if r.status_code == 404:
    eprint(f"{namespace} not found")
  if r.status_code == 403:
    eprint(f"Access denied")
    exit(1)
    
