#!/usr/bin/env python
import sys
import os
import requests
import bouncer
import json
from icecream import ic

url = "http://hexvision.mrflbble.com/path/to/backend.php"

def eprint(*xs,**kw):
  kw['file'] = sys.stderr
  print(*xs,**kw)

args = sys.argv[1:]
if len(args) == 0:
  eprint(f"{sys.argv[0]} <name> [<filename>...]")
  eprint(f"Uses standard input for -, or if no filenames provided")
  exit(1)

def getname(arg):
  if ":" in arg:
    namespace, name = arg.split(":",1)
  else:
    name = arg
    namespace = os.getenv("CLIPNS","_")
  return (namespace,name)

cookies = { bouncer.cookiename: bouncer.cookievalue }

namespace, name = getname(args.pop(0))
if len(args) == 0:
  args = ["-"]
value = []

for arg in args:
  if arg == "-":
    value.append(sys.stdin.read())
  else:
    if os.path.isfile(arg):
      with open(arg) as f:
        value.append(f.read())
    else:
      eprint(f"{arg} is not a file")
if len(value) == 0:
  eprint(f"No content")
value = "\n".join(value)
value = value.replace("\r","")

req = { "namespace": namespace, "name": name, "value": value }
j = json.dumps(req)

r = requests.post(url,data=j,cookies=cookies)
if r.status_code == 200:
  eprint(f"Inserted {namespace}:{name} ({len(value)} bytes)")
elif r.status_code == 400:
  eprint(f"Invalid request",file=sys.stderr)
  exit(1)
elif r.status_code == 500:
  eprint(f"Server error",file=sys.stderr)
  eprint(r.text,file=sys.stderr)
  exit(1)
elif r.status_code == 403:
  eprint(f"Access denied",file=sys.stderr)
  exit(1)
else:
  eprint("WTF",r.status_code,r.text)
  exit(1)
    
