#!/usr/bin/env python
import sys
import os
import requests
import bouncer
import json
from icecream import ic

url = "http://hexvision.mrflbble.com/path/to/backend.php"

def eprint(*xs,**kw):
  kw['file'] = sys.stderr
  print(*xs,**kw)

args = sys.argv[1:]
if len(args) == 0:
  eprint(f"{sys.argv[0]} <name> [<name>...]")
  exit(1)

def getname(arg):
  if ":" in arg:
    namespace, name = arg.split(":",1)
  else:
    name = arg
    namespace = None
  return (namespace,name)

cookies = { bouncer.cookiename: bouncer.cookievalue }

for arg in args:
  namespace, name = getname(arg)
  req = { "namespace": namespace, "name": name }
  j = json.dumps(req)

  r = requests.post(url,data=j,cookies=cookies)
  #print(r.text)
  #print(r.status_code)
  if r.status_code == 200:
    try:
      b = json.loads(r.text)
      if b["message"] == "success":
        items = b['names']
        lens = [ 0 ] * 4
        for item in items:
          item = [ str(x) for x in item ]
          for i, field in enumerate(item):
            lens[i] = max(len(field),lens[i])
        for item in reversed(items):
          a,b,c,d = lens
          e,f,g,h = item
          print(f"{e: >{a}}: {f: >{b}}:{g: <{c}} -- {h}")
      else:
        raise Exception("Didn't succeed")
    except Exception as e:
      eprint("error",r,r.text,e)
  if r.status_code == 404:
    eprint(f"{namespace}:{name} not found")
  if r.status_code == 403:
    eprint(f"Access denied")
    exit(1)
    
