#!/usr/bin/env python
import sys
import os
import requests
import bouncer
import json
from icecream import ic

url = "http://hexvision.mrflbble.com/path/to/backend.php"

def eprint(*xs,**kw):
  kw['file'] = sys.stderr
  print(*xs,**kw)

args = sys.argv[1:]
if len(args) == 0:
  helpexit()

def helpexit(msg=None,retval=1):
  if msg is not None:
    eprint(msg)
  eprint(f"{sys.argv[0]} <name> <clipid>")
  exit(retval)

def getname(arg):
  if ":" in arg:
    namespace, name = arg.split(":",1)
  else:
    name = arg
    namespace = os.getenv("CLIPNS","_")
  return (namespace,name)

cookies = { bouncer.cookiename: bouncer.cookievalue }

try:
  arg, clipid = args
  clipid = int(clipid)
except Exception:
  helpexit("Invalid arguments")

namespace, name = getname(arg)
req = { "namespace": namespace, "name": name, "clipid": clipid }
j = json.dumps(req)

r = requests.post(url,data=j,cookies=cookies)
try:
  b = json.loads(r.text)
except Exception as e:
  eprint("error",r,r.text,e)
  exit(1)
print(r.status_code,b["message"])
